services:
  db:
    image: "postgres:17.0"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  app:
    build: 
      context: .
      dockerfile: ./dev.dockerfile
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    depends_on:
      - db

volumes:
  postgres: