# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: essbio_digital_meters_development
  username: essbio_digital_meters
  password: <%= Rails.application.credentials.dig(:db,:development,:password) %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: essbio_digital_meters_test

production:
  <<: *default
  database: essbio_digital_meters_production
  username: essbio_digital_meters
  password: <%= Rails.application.credentials.dig(:db,:development,:password) %>

